[package]
name = "freq-detector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "freq_detector"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.52"
enum_dispatch = "0.3.7"
rustfft = "6.0.1"
fitting = "0.3.0"
float-cmp = "0.9.0"
num-traits = { version = "0.2", default-features = false }
smoothed_z_score = { git = "https://github.com/mherrerarendon/smoothed_z_score.git" }
apodize = "1.0.0"
plotters = "0.3.1"

[dev-dependencies]
serde_json = "1.0.74"
serde = {version = "1.0.133", features = ["derive"]}

