name: PR and push to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Install the Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Run the pitch-detector crate tests
      working-directory: ./pitch-detector
      run: cargo test
